PlatONnetwork/client-sdk-js

- lib/solidity/coder.js
- lib/utils/toUnicode.js
- lib/utils/utils.js
- lib/web3.js
- lib/web3/contract.js
- lib/web3/function.js
2. Increase the built-in contract CandidateContract
> 1. Implemented the transaction type definition in the Platon protocol

- lib/solidity/coder.js
> 提交0.5.0—dev代码

- lib/web3.js
- lib/web3/function.js
- lib/web3/methods/eth.js
- lib/web3/methods/watches.js
- lib/web3/syncing.js
> 修改了eth模块api的名字以及删除了部分api

- .idea/client-sdk-js.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- .idea/workspace.xml
- README.md
- lib/solidity/coder.js
- lib/solidity/param.js
- lib/utils/config.js
- lib/utils/utils.js
- lib/web3.js
- lib/web3/contract.js
- lib/web3/errors.js
- lib/web3/event.js
- lib/web3/formatters.js
- lib/web3/platon/common.js
- lib/web3/platon/constant.js
- lib/web3/platon/delegateContract.js
- lib/web3/platon/nodeContract.js
- lib/web3/platon/proposalContract.js
- lib/web3/platon/restrctingPlanContract.js
- lib/web3/platon/slashContract.js
- lib/web3/platon/stakingContract.js
- lib/web3/requestmanager.js
sdk版本更新，新增质押、委托、治理、举报惩罚、锁仓计划合约接口，修改货币单位。
> sdk版本更新，新增质押、委托、治理、举报惩罚、锁仓计划合约接口，修改货币单位。

- README.md
> update sample code

- README.md
- packages/web3-eth-accounts/src/index.js
- test/1_platon_http.js
- test/1_platon_wasm.js
> update bech32 address

- packages/web3-eth-contract/src/index.js
> Reassign the network type

- packages/web3-eth-abi/src/index.js
Fix rlp when encoding uint8[], FixedHash type, decoding uint8[][], FixedHash type.
> Fix rlp when encoding uint8[], FixedHash type, decoding uint8[][], FixedHash type.

- packages/web3-eth-abi/src/index.js
> Fixed a bug with evM contract address list parameters

- lib/utils/utils.js
- lib/web3.js
- lib/web3/formatters.js
>  Alaya network unit and Bech32 address format modification for web3j

- packages/web3-eth-abi/src/index.js
- packages/web3-eth-accounts/src/index.js
- packages/web3-eth-contract/src/index.js
- packages/web3-ppos/index.js
- packages/web3-utils/src/ethjs-unit.js
- packages/web3-utils/src/index.js
- packages/web3-utils/src/utils.js
- test/1_platon_http.js
- test/1_platon_ipc.js
- test/1_platon_wasm.js
- test/1_platon_wasm_event.js
- test/1_platon_websocket.js
- test/personal.getAccounts.js
- test/personal.lockAccount.js
- test/personal.newAccount.js
- test/platon.accounts.create.js
- test/platon.accounts.encrypt-decrypt.js
- test/platon.accounts.signTransaction.js
- test/platon.accounts.wallet.js
- test/platon.defaultAccount.js
- test/utils.fromVon.js
- test/utils.toVon.js
- test/vm_fuzz.js
> Alaya network unit and Bech32 address format modification

- README.md
- package.json
> update package name

- packages/web3-eth-accounts/src/index.js
- packages/web3-eth-contract/src/index.js
> fix wallet bug

- packages/web3-eth-contract/src/index.js
> Avoid duplicating definitions

- lib/web3/methods/eth.js
> add api for getAddressHrp

- lib/utils/utils.js
- lib/web3.js
- lib/web3/formatters.js
- lib/web3/methods/eth.js
> update address format and add api for getAddressHrp

- packages/web3-ppos/index.js
> fix bug: handle send tx result

- packages/web3-ppos/index.js
> fix bug: handle send ppos tx result

- packages/web3-ppos/package.json
- packages/web3/package.json
> fix: add web3 ppos dependencies

- packages/web3-eth-contract/src/index.js
fix issue 76.
https://github.com/PlatONnetwork/client-sdk-js/issues/76
> support multi wasm abi

- packages/web3-eth-accounts/src/index.js
Fix [The v implementation of web3.platon.accounts.sign is not match with PlatON-Go](https://github.com/PlatONnetwork/client-sdk-js/issues/63)
> fix web3.platon.accounts.sign
